# Generated by Django 4.2.4 on 2023-09-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cards',
        ),
    ]
