# Generated by Django 4.2.4 on 2023-09-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0004_cards_category_cardvariants_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=400)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='router.cards')),
            ],
        ),
    ]
