# Generated by Django 4.2.4 on 2023-09-07 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0006_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='router.cards')),
                ('filters', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='router.filters')),
            ],
        ),
    ]
