# Generated by Django 4.2.4 on 2023-09-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0007_filtervalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='is_choice',
            field=models.BooleanField(default=False),
        ),
    ]
