# Generated by Django 4.2.5 on 2023-09-19 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('router', '0009_cards_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fio', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('house', models.CharField(max_length=10)),
                ('corps', models.CharField(max_length=10, null=True)),
                ('flat', models.CharField(max_length=10, null=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
