# Generated by Django 4.2.5 on 2023-09-24 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('router', '0010_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delivery', models.BooleanField()),
                ('status', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=300)),
                ('fio', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=30)),
                ('corps', models.CharField(max_length=30)),
                ('room', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('buy_cost', models.FloatField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='router.orders')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='router.cardvariants')),
            ],
        ),
    ]
