# Generated by Django 4.2.5 on 2023-09-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0011_orders_orderentries'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='track',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
